# Generated by Django 3.2 on 2022-03-16 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(max_length=1000)),
                ('vk', models.CharField(max_length=1000)),
                ('facebook', models.CharField(max_length=1000)),
                ('instagram', models.CharField(max_length=1000)),
                ('twitter', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=1000)),
                ('youtube', models.CharField(max_length=1000)),
                ('mainLink', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.contacts'),
        ),
    ]
